# Generated by Django 5.2.17 on 2026-09-25 20:23
# Data step added by hand so the free-text medium survives the column drop.

from django.db import migrations, models

# Historical models from apps.get_model() carry no custom attributes, so the
# category is spelled out here rather than using Tag.MEDIUM.
MEDIUM = 'medium'


def medium_text_to_tags(apps, schema_editor):
    """Carry each artwork's free-text medium into its tags before the column goes.

    Artworks that already carry a medium tag are skipped. That matters for the
    seeded piece whose medium was 'graphite and charcoal' while its tags were
    already ['graphite', 'charcoal'] -- converting the text naively would have
    created a junk 'graphite and charcoal' tag next to the two correct ones.
    """
    Artwork = apps.get_model('artworks', 'Artwork')
    Tag = apps.get_model('artworks', 'Tag')

    for artwork in Artwork.objects.prefetch_related('tags'):
        if any(tag.category == MEDIUM for tag in artwork.tags.all()):
            continue

        name = (artwork.medium or '').strip()
        if not name:
            continue

        tag = Tag.objects.filter(name__iexact=name, category=MEDIUM).first()
        if tag is None:
            # Tag.name is unique across every category, so a name already taken
            # by a technique or subject tag cannot be recreated as a medium.
            taken = Tag.objects.filter(name__iexact=name).exists()
            if taken:
                print(
                    f'  ! "{artwork.title}": medium {name!r} clashes with an '
                    f'existing non-medium tag; left without a medium tag.'
                )
                continue
            tag = Tag.objects.create(name=name, category=MEDIUM)

        artwork.tags.add(tag)


def tags_to_medium_text(apps, schema_editor):
    """Best-effort reverse: put the first medium tag back into the text column."""
    Artwork = apps.get_model('artworks', 'Artwork')

    for artwork in Artwork.objects.prefetch_related('tags'):
        names = [tag.name for tag in artwork.tags.all() if tag.category == MEDIUM]
        if names:
            artwork.medium = names[0]
            artwork.save(update_fields=['medium'])


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        # Order matters: the data step still needs to read artwork.medium.
        migrations.RunPython(medium_text_to_tags, tags_to_medium_text),
        # Giving the column a default before dropping it is what makes this
        # migration reversible. Reversing runs these backwards, so RemoveField
        # re-adds the column using the definition recorded *here* -- and the
        # original NOT NULL CharField with no default cannot be added back to a
        # table that already has rows.
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='medium',
        ),
    ]
