# Generated by Django 5.2.17 on 2026-09-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_remove_artwork_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='critiquerequest',
            name='artist_note',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
