# Generated by Django 5.2.17 on 2026-09-16 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Critique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to='artworks.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CritiqueSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('composition', 'Composition'), ('color', 'Color'), ('technique', 'Technique'), ('concept', 'Concept'), ('perspective', 'Perspective')], max_length=20)),
                ('body', models.TextField()),
                ('section_type', models.CharField(choices=[('strength', 'Strength'), ('growth', 'Area for growth')], max_length=10)),
                ('critique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='critiques.critique')),
            ],
        ),
    ]
