# Generated by Django 5.2.17 on 2026-09-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critiques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critiquesection',
            name='section_type',
        ),
    ]
